stages:
  - code_test

.code_check: &code_check
  image: robbrazier/php:7.2
  script:
    - php -v
    - composer require --dev --no-update --ansi jakub-onderka/php-parallel-lint:"1.*"
    - composer update --no-scripts --prefer-dist --ansi
    - ./vendor/bin/parallel-lint -e php,php3,php4,php5,phtml,phpt,phps --exclude vendor .

code_check_72:
    <<: *code_check
    image: robbrazier/php:7.2
    stage: code_test

whitespace_check:
  image: robbrazier/php:7.2
  stage: code_test
  script:
    - if grep --include=*.{php,php3,php4,php5,phtml,phpt,phps} -rl $'\xEF\xBB\xBF' .; then echo 'Files contains unicode byte order mark (BOM)!'; exit 1; fi
    - if grep -rlP --include=\*.{cs,php,phpt} '[[:blank:]](\r)?$' .; then echo 'Please remove trailing whitespace'; exit 1; fi
    - if grep -rlP --include=\*.{php,phpt} '\r' .; then echo 'Please save with UNIX line endings'; exit 1; fi

phpstan_project_tests:
  image: robbrazier/php:7.2
  stage: code_test
  allow_failure: false
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - log/
  script:
    - composer update --no-scripts --prefer-dist --ansi
    - ./vendor/bin/phpstan analyse -l7 -c ./tests/phpstan/phpstan.neon app

php_code_standard:
  image: robbrazier/php:7.2
  stage: code_test
  allow_failure: false
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - log/
  script:
    - composer update --no-scripts --prefer-dist --ansi
    - ./vendor/bin/phpcs -p --standard=./tests/php_codesniffer/ruleset.xml app

nette_code_checker:
  image: robbrazier/php:7.2
  stage: code_test
  allow_failure: false
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - log/
  script:
    - rm -rf ../code_checker
    - composer create-project nette/code-checker ../code_checker
    - ../code_checker/code-checker --ignore *.php --ignore *.neon --no-progress -d `pwd`/app/
    - rm -rf ../code_checker

php_copy_detector:
    image: robbrazier/php:7.2
    stage: code_test
    allow_failure: false
    script:
        - rm -rf ../php_cpd
        - composer create-project sebastian/phpcpd ../php_cpd
        - ../php_cpd/phpcpd `pwd`/app/
        - rm -rf ../php_cpd
